/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./components/Anchor.vue')['default']
    AppBar: typeof import('./components/Layout/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumbs: typeof import('./components/Layout/Breadcrumbs.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    LanguageSwitcher: typeof import('./components/Layout/LanguageSwitcher.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Menu: typeof import('./components/Layout/Menu.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageBox: typeof import('./components/MessageBox.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./components/Layout/UserInfo.vue')['default']
  }
}
