/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/chart-table': RouteRecordInfo<'/chart-table', '/chart-table', Record<never, never>, Record<never, never>>,
    '/charts': RouteRecordInfo<'/charts', '/charts', Record<never, never>, Record<never, never>>,
    '/datetime-demo': RouteRecordInfo<'/datetime-demo', '/datetime-demo', Record<never, never>, Record<never, never>>,
    '/drawer-demo': RouteRecordInfo<'/drawer-demo', '/drawer-demo', Record<never, never>, Record<never, never>>,
    '/input-demo': RouteRecordInfo<'/input-demo', '/input-demo', Record<never, never>, Record<never, never>>,
    '/kpi-overview': RouteRecordInfo<'/kpi-overview', '/kpi-overview', Record<never, never>, Record<never, never>>,
    '/loading-demo': RouteRecordInfo<'/loading-demo', '/loading-demo', Record<never, never>, Record<never, never>>,
    '/notification-demo': RouteRecordInfo<'/notification-demo', '/notification-demo', Record<never, never>, Record<never, never>>,
    '/os-usage': RouteRecordInfo<'/os-usage', '/os-usage', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/chart-table.vue': {
      routes: '/chart-table'
      views: never
    }
    'src/pages/charts.vue': {
      routes: '/charts'
      views: never
    }
    'src/pages/datetime-demo.vue': {
      routes: '/datetime-demo'
      views: never
    }
    'src/pages/drawer-demo.vue': {
      routes: '/drawer-demo'
      views: never
    }
    'src/pages/input-demo.vue': {
      routes: '/input-demo'
      views: never
    }
    'src/pages/kpi-overview.vue': {
      routes: '/kpi-overview'
      views: never
    }
    'src/pages/loading-demo.vue': {
      routes: '/loading-demo'
      views: never
    }
    'src/pages/notification-demo.vue': {
      routes: '/notification-demo'
      views: never
    }
    'src/pages/os-usage.vue': {
      routes: '/os-usage'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
